name: Push OK
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  say-ok:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decir OK en consola
        run: |
          echo "OK: se ejecutó el workflow correctamente"

      